### PR TITLE
Create a 'publishedCursor' function

### PR DESCRIPTION
**Pull request by m-vinc**
Hi
I have an idea to improve your package, I just add a function to the object passed to publishPagination  named publishedCursor which is called with the cursor you use to observeChange. This allow me to publish some related cursor and avoid the creation of a second publication to publish that related stuff.

Here is an example of a pagination which publish some events and their category

```
publishPagination(Events, {
    filters: {},
    dynamic_filters () {
        return {};
    },
    transform_filters (filters) {
        return filters
    },
    transform_options (filters, options) {
        options.fields = {name: 1, category: 1}
        return options;
    },
    publishedCursor (cursor) {
      return [
        Categories.find({ _id: { $in: cursor.map(x => x.category) } }, { fields: { name: 1 } })
      ]
    }
});

```

### CODE REVIEW

**Comment by m-vinc** [comment]
I just notice my linter just format all your code with standardjs, don't be afraid of the diff i just add 4 lines of code ahah ( the changes is from line 134 to 137)

**Comment by Kurounin** [comment]
Seems like a good feature, but:
- you are not calling `ready()` on the publication
- when a subscription is not reactive the related documents are not published

**Comment by m-vinc** [comment]
Hi,
I'm not sure if we need to call sub.ready if we return a cursor or an array of cursor in a publication
and of course i just modify the case when the pagination is reactive to do some test and submit the idea to know if this is suitable :)

**Comment by Kurounin** [comment]
You're right, it seems that when a cursor is returned there's no need to call the `ready()` method.
Thanks for the PR. I'm still thinking if it makes sense to include this, because I'd like to keep it working in both reactive and non-reactive modes. Also I'm not sure if problems might be created when publishing the related collection (there might be edge cases that need to be treated when a document gets deleted or modified).

**Comment by Kurounin** [comment]
Sorry for the late response, but only now I had time to go over the changes and test them.
Unfortunately the current implementation has a major flaw in that any changes done to the documents returned by the initial cursor are not propagated the `publishedCursor` method so you are left with possibly invalid related documents.
Since this is not an easy fix and there are packages that specialize in tracking the changes and ensuring the correct related documents are published I'll have to reject the current PR, but thank you for submission.

**Pull request closed without merging**
